apiVersion: apps/v1
kind: Deployment
metadata:
  name: megabudget
spec:
  template:
    spec:
      containers:
        - name: megabudget
          image: registry.lan:5000/megabudget:prod-2026-01-14
          envFrom:
            - secretRef:
                name: megabudget-prod-db-secret
