apiVersion: apps/v1
kind: Deployment
metadata:
  name: spendtrack
spec:
  template:
    spec:
      containers:
        - name: spendtrack
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: spendtrack-prod-db-secret
                  key: DATABASE_URL
