apiVersion: v1
kind: Service
metadata:
  name: megabudget
  labels:
    app: megabudget
spec:
  type: ClusterIP
  selector:
    app: megabudget
  ports:
    - name: http
      port: 8080
      targetPort: http
