apiVersion: v1
kind: Service
metadata:
  name: spendtrack
  labels:
    app: spendtrack
spec:
  type: ClusterIP
  selector:
    app: spendtrack
  ports:
    - name: http
      port: 8080
      targetPort: http
